(function(){
"use strict";
var screen="home",focus=null,history=[],anime="One Piece";
function $(s){return document.querySelector(s)} function all(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function toast(t){var x=$("#toast");x.textContent=t;x.style.display="block";clearTimeout(toast.t);toast.t=setTimeout(function(){x.style.display="none"},1000)}
function fs(){return all("#"+screen+" .focusable").filter(function(x){return x.offsetWidth&&x.offsetHeight&&!x.disabled})}
function setf(x){if(focus)focus.classList.remove("focused");focus=x||null;if(focus){focus.classList.add("focused");try{focus.scrollIntoView({block:"center",inline:"center",behavior:"smooth"})}catch(e){}}}
function first(){setf(fs()[0]||null)}
function open(n,push){if(push&&n!==screen)history.push(screen);all(".screen").forEach(function(x){x.classList.remove("active")});$("#"+n).classList.add("active");screen=n;setf(null);setTimeout(first,40)}
function openAnime(n){anime=n;$("#animeTitle").textContent=n;var box=$("#episodeCards");box.innerHTML="";for(var i=1;i<=12;i++){var b=document.createElement("button");b.className="card focusable";b.dataset.episode=i;b.innerHTML="<b>Episode "+i+"</b><small>"+n+"</small>";box.appendChild(b)}open("anime",true)}
function search(){var q=$("#searchInput").value.trim(),box=$("#searchResults");box.innerHTML="";if(!q){toast("Type an anime name");$("#searchInput").focus();return}["One Piece","Naruto","Jujutsu Kaisen","Demon Slayer"].forEach(function(n){if(n.toLowerCase().indexOf(q.toLowerCase())>=0){var b=document.createElement("button");b.className="card focusable";b.dataset.anime=n;b.innerHTML="<b>"+n+"</b><small>Demo result</small>";box.appendChild(b)}});setTimeout(first,30)}
function activate(x){if(!x)return;if(x.tagName==="INPUT"){x.focus();return}var a=x.dataset.action;if(x.dataset.anime)openAnime(x.dataset.anime);else if(a==="search")open("search",true);else if(a==="do-search")search();else if(a==="anime")openAnime(anime);else if(a==="servers")open("servers",true);else if(a==="player"){open("player",true);$("#playerTitle").textContent=anime+" • Episode 1"}else if(x.dataset.episode)toast("Episode "+x.dataset.episode)}
function move(dir){var f=fs();if(!f.length)return;if(!focus||f.indexOf(focus)<0){first();return}var r=focus.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,best=null,score=1e9;f.forEach(function(x){if(x===focus)return;var z=x.getBoundingClientRect(),dx=z.left+z.width/2-cx,dy=z.top+z.height/2-cy,p,s;if(dir==="left"){if(dx>=-5)return;p=-dx;s=Math.abs(dy)}else if(dir==="right"){if(dx<=5)return;p=dx;s=Math.abs(dy)}else if(dir==="up"){if(dy>=-5)return;p=-dy;s=Math.abs(dx)}else{if(dy<=5)return;p=dy;s=Math.abs(dx)}var v=p+s*1.5;if(v<score){score=v;best=x}});if(best)setf(best)}
document.addEventListener("keydown",function(e){var k=e.keyCode,a=document.activeElement;if(a&&a.tagName==="INPUT"&&(k===37||k===39||k===8||k===46))return;if(k===37){move("left");e.preventDefault()}else if(k===38){move("up");e.preventDefault()}else if(k===39){move("right");e.preventDefault()}else if(k===40){move("down");e.preventDefault()}else if(k===13){if(a&&a.tagName==="INPUT")return;activate(focus);e.preventDefault()}else if(k===10009){if(a&&a.tagName==="INPUT"){a.blur();return}if(history.length)open(history.pop(),false);else open("home",false);e.preventDefault()}else if(k===10252)toast("Play / Pause");else if(k===412)toast("−10 seconds");else if(k===417)toast("+10 seconds")});
setTimeout(first,100);
})();
