(function(){'use strict';
var BACKEND=localStorage.getItem("miruroBackend")||"https://public-miruro-consumet-api.vercel.app";
var USE_PROXY=true;
var PROXY="https://corsproxy.io/?url=";
var statusEl=document.getElementById("status"),screens=document.querySelectorAll(".screen"),currentAnime=null;
function status(s){statusEl.textContent=s}
function show(id){for(var i=0;i<screens.length;i++)screens[i].classList.remove("active");document.getElementById(id).classList.add("active");var f=document.querySelector("#"+id+" .focusable");if(f)try{f.focus()}catch(e){}}
function esc(s){return String(s||"").replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
function api(path){var u=BACKEND.replace(/\/$/,"")+path;var target=USE_PROXY?PROXY+encodeURIComponent(u):u;return fetch(target,{headers:{"Accept":"application/json"}}).then(function(r){if(!r.ok)throw Error("HTTP "+r.status);return r.json()})}
function id(a){return a.id||""}
function title(a){var t=a.title;if(typeof t==="string")return t;return t&&(t.english||t.romaji||t.userPreferred||t.native)||a.name||"Unknown"}
function image(a){return a.image||a.cover||a.poster||a.thumbnail||(a.coverImage&&(a.coverImage.extraLarge||a.coverImage.large||a.coverImage.medium))}
function list(d){return Array.isArray(d)?d:(d.results||d.data||d.animes||d.items||[])}
function cards(items,target){var el=document.getElementById(target);el.innerHTML="";if(!items.length){el.innerHTML='<div class="player-message">No results found.</div>';return}items.slice(0,30).forEach(function(a){var b=document.createElement("button");b.className="card focusable";b.innerHTML='<img src="'+esc(image(a)||"https://via.placeholder.com/300x420?text=Anime")+'"><div class="name">'+esc(title(a))+'</div><div class="meta">'+esc((a.releaseDate||"")+" "+(a.subOrDub||""))+"</div>";b.onclick=function(){openAnime(a)};el.appendChild(b)})}
function search(q){status("Searching…");api("/anime/gogoanime/"+encodeURIComponent(q)+"?page=1").then(function(d){cards(list(d),"results");status("Ready")}).catch(function(e){status("Search error");document.getElementById("results").innerHTML='<div class="player-message">Search failed: '+esc(e.message)+'</div>'})}
function openAnime(a){currentAnime=a;show("details");document.getElementById("detailsBox").innerHTML='<div class="title">'+esc(title(a))+'</div><div class="desc">Loading information…</div>';document.getElementById("episodes").innerHTML='<div class="player-message">Loading episodes…</div>';api("/anime/gogoanime/info/"+encodeURIComponent(id(a))).then(function(d){currentAnime=d;document.getElementById("detailsBox").innerHTML='<div class="title">'+esc(title(d))+'</div><div class="desc">'+esc(d.description||d.synopsis||"")+'</div>';var eps=d.episodes||d.episodeList||[];var box=document.getElementById("episodes");box.innerHTML="";eps.forEach(function(ep,i){var b=document.createElement("button");b.className="ep focusable";b.textContent="Episode "+(ep.number||ep.episodeNumber||i+1);b.onclick=function(){playEpisode(ep)};box.appendChild(b)});if(!eps.length)box.innerHTML='<div class="player-message">No episodes returned.</div>'}).catch(function(e){document.getElementById("episodes").innerHTML='<div class="player-message">Anime info failed: '+esc(e.message)+'</div>'})}
function playEpisode(ep){show("player");var m=document.getElementById("playerMessage"),v=document.getElementById("video");m.style.display="block";v.style.display="none";m.textContent="Loading episode…";var eid=ep.id||ep.episodeId;if(!eid){m.textContent="This episode has no usable ID.";return}api("/anime/gogoanime/watch/"+encodeURIComponent(eid)).then(function(d){var s=d.sources&&d.sources[0];if(!s){m.textContent="The backend did not return a playable source.";return}var u=s.url||s.file;if(!u){m.textContent="No playable URL returned.";return}v.src=u;v.style.display="block";m.style.display="none";try{v.play()}catch(e){}}).catch(function(e){m.textContent="Playback request failed: "+e.message})}
function loadHome(){status("Loading…");api("/anime/gogoanime/recent-episodes?page=1").then(function(d){cards(list(d),"homeGrid");status("Ready")}).catch(function(e){status("Backend unavailable");document.getElementById("homeGrid").innerHTML='<div class="player-message">Could not reach the configured backend. Search can still be tested from the Search screen.</div>'})}
document.addEventListener("keydown",function(e){var k=e.keyCode||e.which;if(k===10009||k===461){e.preventDefault();show("home")}if(k===415){var v=document.getElementById("video");if(v){if(v.paused)v.play();else v.pause()}}if(k===412){var v=document.getElementById("video");if(v)v.currentTime=Math.max(0,v.currentTime-10)}if(k===417){var v=document.getElementById("video");if(v)v.currentTime+=10}});
document.addEventListener("click",function(e){var a=e.target.closest&&e.target.closest("[data-action]");if(!a)return;var x=a.getAttribute("data-action");if(x==="search")show("search");if(x==="recent")loadHome();if(x==="popular"){status("Loading…");api("/anime/gogoanime/top-airing?page=1").then(function(d){cards(list(d),"homeGrid");status("Ready")}).catch(function(){status("Popular unavailable")})}if(x==="do-search"){var q=document.getElementById("query").value.trim();if(q)search(q)}});
window.addEventListener("load",loadHome);
})();
